discord: https://discord.gg/ESvqmEF4vA
github: https://github.com/williamjaackson/griffith-ict-web/
linkedin: https://www.linkedin.com/company/griffithtechorg/
instagram: http://instagram.com/griffithictclub
email: william@jaackson.com

campus_groups:
  gold_coast: https://griffith.campusgroups.com/GIC/club_signup
  brisbane: https://griffith.campusgroups.com/GICT/club_signup
