name: Checks

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: checks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1
        with:
          bundler-cache: true

      - name: Run CI
        run: bin/ci
